#!/bin/sh
# Send the informations to Event Browser (gedq)
#
# --- Input arguments
#	var1	Contract -> CONTRACT="SCC"
#	var2	Site -> SITE="`hostname`"
#	var3	Priority -> PRIO=1
#	var4	Criticity -> CRIT=1
#	var5	extref_incident -> extref_incident=""


# 	arg1	$HOSTNAME$
#	arg3	$SERVICEDESC$ 
#	arg4	$HOSTSTATE$ 
#	arg5	$HOSTOUTPUT$
#	arg6	$HOSTADDRESS$
#	arg7	$HOSTALIAS$
#	arg8	$HOSTGROUPS$

bin="/srv/rgm/ged/bin/gedq"
. /srv/rgm/ged/etc/event_rgm.cfg

case "$3" in
  UP)
        $bin -push -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UP" 0 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UP" 0
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST DOWN" 2
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UNREACHABLE" 2
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "UNKNOWN" 3 
        ;;
  DOWN)
        $bin -push -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST DOWN" 2 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UP" 0
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UNREACHABLE" 2
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "UNKNOWN" 3 
        ;;
  UNREACHABLE)
        $bin -push -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UNREACHABLE" 2 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UP" 0
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST DOWN" 2
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "UNKNOWN" 3 
        ;;
  *)
        $bin -push -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "UNKNOWN" 3 "" "$4" "$5" "$6" "$7"
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UP" 0
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST DOWN" 2
        $bin -drop -type 1 "$CONTRACT" "$SITE" "$PRIO" "$CRIT" "0" "0" "$extref_incident" "$1" "HOST UNREACHABLE" 2
        exit 1
esac

exit 0


